name: objcxp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-93.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  ffigen:
    path: /Users/goderbauer/dev/native/pkgs/ffigen
  lints: ^6.0.0
  test: ^1.25.6
  objective_c:
    path: /Users/goderbauer/dev/native/pkgs/objective_c
